set autoindent
set background=dark
set encoding=utf-8
set expandtab
set ignorecase
set laststatus=2
set list
set number
set ruler
set shiftwidth=0 "use tabstop value
set smartcase
set smartindent
set splitbelow
set tabstop=2
if v:version >= 900
  set listchars=eol:↲,tab:>\\x20
endif
if v:version >= 902
  set autocomplete
endif

if has('extra_search')
  set hlsearch
  set incsearch
endif
if has('mouse')
  set mouse=a
endif
if has('syntax')
  set cursorline
  set spelllang=en,cjk
  if v:version >= 900
    set spelloptions=camel
  endif
endif
if has('termguicolors')
  set termguicolors
endif
if has('unnamedplus')
  set clipboard^=unnamedplus
elseif has('clipboard_provider')
  set clipboard^=unnamed
endif

syntax enable
filetype plugin indent on

try
  colorscheme iceberg
catch /^Vim\%((\a\+)\)\=:E185/
  "ignore error
endtry

nnoremap <silent> <Esc><Esc> :nohlsearch<CR>
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> tt :tabnew<CR>
nnoremap <silent> [t :tabprevious<CR>
nnoremap <silent> ]t :tabnext<CR>
nnoremap <silent> tm :terminal<CR>

if v:version >= 800
  packadd! editorconfig
endif

" vim-airline
let g:airline_powerline_fonts = 1

" caw.vim
let g:caw_no_default_keymappings = 1
nnoremap <silent> <C-_> <plug>(caw:hatpos:toggle)
xnoremap <silent> <C-_> <plug>(caw:hatpos:toggle)
nnoremap <silent> <C-BSlash> <plug>(caw:wrap:toggle)
xnoremap <silent> <C-BSlash> <plug>(caw:wrap:toggle)

" NERDTree
let g:NERDTreeWinSize = min([&columns / 4, 48])
nnoremap <silent> <C-n> :NERDTreeToggle<CR>

" previm
let g:previm_custom_preview_base_dir = expand('$XDG_CACHE_HOME/previm')
let g:previm_enable_realtime = 1
let g:previm_show_header = 0
