[shell]
program = "bash"
args = ["-l", "-c", "tmux attach-session -t 0 || tmux new-session"]

[window]
padding = { x = 4, y = 0 }
startup_mode = "Maximized"

[font]
normal = { family = "UDEV Gothic NFLG", style = "Regular" }
size = 14.5

[colors.primary]
foreground = "#c6c8d1"
background = "#161821"

[colors.normal]
black = "#161821"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#c6c8d1"

[colors.bright]
black = "#6b7089"
red = "#e98989"
green = "#c0ca8e"
yellow = "#e9b189"
blue = "#91acd1"
magenta = "#ada0d3"
cyan = "#95c4ce"
white = "#d2d4de"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]
